# Enable experimental BLE settings for better connection stability and auto-recovery
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Enable experimental BLE security to allow unauth overwriting of old peripheral bonds
CONFIG_ZMK_BLE_EXPERIMENTAL_SEC=y

# Disable 2Mbps PHY. This is a known fix for connection instability on PC/Mac Bluetooth chipsets
CONFIG_BT_CTLR_PHY_2M=n
